// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSXAuYWj_taFxtIEozY5LSTBqVEAA1zdc',
    appId: '1:25741001724:web:b7aa3e8a3faf37dbf2a879',
    messagingSenderId: '25741001724',
    projectId: 'start-fe911',
    authDomain: 'start-fe911.firebaseapp.com',
    storageBucket: 'start-fe911.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAisf6j1kOuG_c7kO5KxeW7xupC_G_3ca4',
    appId: '1:25741001724:android:294ecff697ff5351f2a879',
    messagingSenderId: '25741001724',
    projectId: 'start-fe911',
    storageBucket: 'start-fe911.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEW6ib4vd3dYszQe5RDB67JyOBmnaqvsk',
    appId: '1:25741001724:ios:4ce51554086569d6f2a879',
    messagingSenderId: '25741001724',
    projectId: 'start-fe911',
    storageBucket: 'start-fe911.appspot.com',
    iosBundleId: 'com.example.start',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSXAuYWj_taFxtIEozY5LSTBqVEAA1zdc',
    appId: '1:25741001724:web:1dafbc6861c8086af2a879',
    messagingSenderId: '25741001724',
    projectId: 'start-fe911',
    authDomain: 'start-fe911.firebaseapp.com',
    storageBucket: 'start-fe911.appspot.com',
  );
}
